[build]
  base = "pweb/backend"
  command = "echo 'No build step required'"
  publish = "."
  functions = "netlify/functions"  # Ensure the correct functions folder is specified

[dev]
  functions = "netlify/functions"  # Same for dev functions folder
  publish = "build"

[context.production.environment]
  NODE_ENV = "production"

[build.environment]
  MONGODB_URI = "your_mongodb_connection_string_here"
  JWT_SECRET = "your_jwt_secret_here"
